### ISSUE TITLE
Null safety migration

### ISSUE THREAD

**Issue by znjameswu** [znjameswu/flutter_math#15]
The manual nnbd migration turns out to be easier than I had thought. Currently all tests are passing on the `nnbd` branch.

The prerelease version will be published once the following dependencies have migrated:
- `provider`
- `flutter_svg`
- `tuple` (currently replaced with an internal implementation)

**Comment by creativecreatorormaybenot** [comment]
You should probably **redo** some parts of the migration once upstream has migrated. Otherwise, you will lose the nullability information and just assume that everything from `upstream` that was not yet migrated is nullable.

I can also do that migration if you are interested :)

**Comment by znjameswu** [comment]
> You should probably **redo** some parts of the migration once upstream has migrated. Otherwise, you will lose the nullability information and just assume that everything from `upstream` that was not yet migrated is nullable.
> 
> I can also do that migration if you are interested :)

Yes, that's the reason I've not yet merged it into the master. You can work on the nnbd branch.

**Comment by creativecreatorormaybenot** [comment]
@znjameswu Sounds good - let's hope I will remember to do it once the packages have been migrated 😄

**Comment by znjameswu** [comment]
@creativecreatorormaybenot `provider` was updated yesterday so I've tried to update dependencies and they just seem to work. You can check them on the `nnbd` branch.

**Comment by creativecreatorormaybenot** [comment]
@znjameswu Yep, nice! Looking good; great that all dependencies have the NNBD version now 😋 

I think `provider` has had the null safety version for about a week now, but I completely forgot about this issue 🙈 

Does that mean that you are done with the migration already? Or should I take a look into migrating it?  
Would probably migrate from the `master` version - but no need to bother with it when you say that it is already done.

**Comment by znjameswu** [comment]
@creativecreatorormaybenot Yes I think I'm done with migrating and shall merge `nnbd` branch into `master`.
