### ISSUE TITLE
Overflow in `cases` environment

### ISSUE THREAD

**Issue by Skyost** [znjameswu/flutter_math#17]
Hey,

First, thank you for this great plugin ! I'm currently trying to implement it in my app alongside `flutter_widget_from_html_core`. But everytime I'm using the `cases` environment, I get a `RenderLine overflowed of 16 pixels` error.

<img height="400" src="https://user-images.githubusercontent.com/3882599/100631369-ef84cc00-332b-11eb-9116-cf01ce730caf.png">

(the second overflow error is due to #8)

The `Math` widget is inserted as an inline widget and its parent is a `Column` widget.

**Comment by znjameswu** [comment]
Thank you for your feedback. I'll check that. Possibly missing some tests.

Meanwhile as a suggestion, for display equation overflow caused by #8, you can always wrap it inside a scrollable widget.

**Comment by Skyost** [comment]
> Meanwhile as a suggestion, for display equation overflow caused by #8, you can always wrap it inside a scrollable widget.

Yes, that's what I figured out too. But the thing is that I don't like when these blocks are scrollable, because `Text` widgets do not wrap. For example,

Not in a scrollable widget :
```
Lorem ipsum dolor sit amet, consectetur adipiscing elit.
Nunc gravida ex eu velit sagittis laoreet. Pellentesque placerat
urna ut tempus molestie.

Morbi feugiat ornare orci sed pharetra. Aliquam elit ligula,
bibendum sit amet mi eget, porttitor lobortis nisi. Etiam mattis
tempor pellentesque.
```

In a scrollable widget :
```
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc gravida ex eu velit sagittis laoreet. Pellentesque placerat urna ut tempus molestie.

Morbi feugiat ornare orci sed pharetra. Aliquam elit ligula, bibendum sit amet mi eget, porttitor lobortis nisi. Etiam mattis tempor pellentesque.
```

(and I prefer the first one, but I also think I will have to implement the second one.) It would be great if Flutter allowed us to detect when an overflow occurs (so that I can use scrollable widgets only when needed), but I don't think it's possible, sadly 😄

**Comment by znjameswu** [comment]
It is a combination of corner cases inside `RenderLine` layout logic and parsing flaws for `cases` environment without second column. I'll fix it sometime later this week.

**Comment by Skyost** [comment]
Great @znjameswu !

**Comment by Skyost** [comment]
Hey @znjameswu, do you have any news about this one ?

**Comment by znjameswu** [comment]
> Hey @znjameswu, do you have any news about this one ?

Sorry I'm having quite a burnout recently. I will work on this one as soon as possible.

**Comment by Skyost** [comment]
Take your time @znjameswu, I know what it is to be completely overwhelmed with work.

**Comment by Skyost** [comment]
Thanks a lot !
