### ISSUE TITLE
Math.tex(r'\frac a b') will throws an error

### ISSUE THREAD

**Issue by panmengma** [znjameswu/flutter_math#18]
Math.tex(r'\frac a b');
Math.tex(r'\frac a b', mathStyle: MathStyle.display);
Math.tex(r'\frac a b', mathStyle: MathStyle.text);

The above code all will throw a same error:
NoSuchMethodError: The getter 'color' was called on null.
Receiver: null
Tried calling: color

My development environment is win10+vscode.

**Comment by Skyost** [comment]
I don't know if it's a bug or anything, but you have to pass a `TextStyle` with a non-null color :

`Math.tex(r'\frac a b', TextStyle(color: Colors.black));`

**Comment by panmengma** [comment]
> I don't know if it's a bug or anything, but you have to pass a `TextStyle` with a non-null color :
> 
> `Math.tex(r'\frac a b', textStyle: TextStyle(color: Colors.black));`

Thanks for your response.

I finally get the code running correctly following your suggestions.

What puzzles me is why the usage like Math.tex(r'\frac a b', mathStyle: MathStyle.display) , Math.tex(r'\frac a b',textStyle: TextStyle(fontSize: 42)) which is in the documentation will throw an error?

**Comment by Skyost** [comment]
Depends on your testing environment, I think. If you provide a default color to your app text style, then it's all good. Otherwise you will encounter this error (that's what I understood from my investigations).

**Comment by panmengma** [comment]
> Depends on your testing environment, I think. If you provide a default color to your app text style, then it's all good. Otherwise you will encounter this error (at least, that's what I understood from my investigations).
> 
> I could submit a pull request to fix this one as it doesn't seem to be too complicated.

Yes, I agree with you.

 And, Thanks for your work!

**Comment by znjameswu** [comment]
Sorry for the delay. Yeah, I can confirm confirm it is a bug. Thank you @Skyost !
