### ISSUE TITLE
CaTeX link

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [znjameswu/flutter_math#21]
Hi James,

I have been linking to `flutter_math` from new issues created on [`CaTeX`](https://github.com/simpleclub/CaTeX) for quite a while now. You might have noticed that we have been quite busy since we created that repo and have not been able to actively maintain it.

Because of that, I want to add an on-hold notice to the package and I would like to link to `flutter_math` in there:

![image](https://user-images.githubusercontent.com/19204050/102288126-b6577900-3f33-11eb-824e-298135e2ef38.png)

Does this look good to you? I have to still check with my colleagues if this works for them, however, I wanted to make sure that this is fine with you first :)

---

By the way, I am not sure if you remember. `CaTeX` had > 100 stars the days after we launched. At some point, we took it private by accident, which completely reset everything. So that is that in case you were curious 🙂

And we are still super excited about the TeX in Flutter project! It is also why we decided to still try to work together as much as possible, even when our priorities were shifted.

**Comment by creativecreatorormaybenot** [comment]
@znjameswu I pushed it to `master` now, so it is live :) 

Let me know if you have any concerns 👍

**Comment by znjameswu** [comment]
Thank you for that! I appreciate it!
