### ISSUE TITLE
Alignment in line breaking mode

### ISSUE THREAD

**Issue by Skyost** [znjameswu/flutter_math#29]
Hey,

I've followed the instructions [here](https://github.com/znjameswu/flutter_math/blob/master/doc/line_breaking.md#standard-tex-style-quick-start) to implement the line breaking feature in my app. It really suits my needs, but there's a little caveat using a `Wrap` widget in order to display Tex break parts : some parts are not aligned. Here are some examples :

![Screenshot_1](https://user-images.githubusercontent.com/3882599/104939924-51b79000-59b1-11eb-9935-7e2f8ef09a0d.png)
![Screenshot_2](https://user-images.githubusercontent.com/3882599/104939927-52502680-59b1-11eb-8323-87fe6cd580a0.png)
![Screenshot_3](https://user-images.githubusercontent.com/3882599/104939929-52502680-59b1-11eb-844e-6cf64e3ca819.png)

Is there a way to align the `Math` widgets in a `Wrap` ?

Thanks !

**Comment by MuratovArthur** [comment]
@Skyost

Hey! 

I am a beginner in flutter, so I couldn't use the author's documentation to implement the line-breaking feature correctly. I have an error: `Error: The method 'texBreak' isn't defined for the class 'Math'.`

Could you help me? Could you share your code?

**Comment by Skyost** [comment]
@MuratovArthur You have to install the dev version from git (see [here](https://github.com/Skyost/Bacomathiques/blob/app/pubspec.yaml#L32)).

**Comment by MuratovArthur** [comment]
@Skyost 

Hey!

Thank you for helping me!

I've tried to install the dev version from git, but it required to update some other packages. I've updated `sdk` to `sdk: ">=2.6.0 <3.0.0"`, `flutter_svg` to `flutter_svg: ^0.20.0-nullsafety.3`. 

After that, I've tried to run my app, but there was an error `Error: Too few positional arguments: 8 required, 7 given.
            child: selectionControls!.buildToolbar(`.

Did you face such an error?)

**Comment by Skyost** [comment]
@MuratovArthur Nope because I'm not using `selectionControls.buildToolbar`, but the error is only telling you that you're missing an argument at that line.

**Comment by Skyost** [comment]
I finally have some results using the following code :

```dart
@override
Widget build(BuildContext context) {
  Math math = Math.tex(input);

  List<Math> parts = math.texBreak().parts;
  if (parts.length == 1) {
    return parts.first;
  }

  return RichText(
    text: TextSpan(
      children: _handleParts(parts),
    ),
  );
}

List<InlineSpan> _handleParts(List<Math> parts) {
  List<InlineSpan> result = [];
  for (Math part in parts) {
    result.add(WidgetSpan(
      baseline: TextBaseline.alphabetic,
      alignment: PlaceholderAlignment.baseline,
      child: part,
    ));
    result.add(const TextSpan(
      text: ' ',
    ));
  }
  return result;
}
```

I don't think it's the best way to achieve this, but at least it works.

**Comment by yavuztarhan** [comment]
> @MuratovArthur You have to install the dev version from git (see [here](https://github.com/Skyost/Bacomathiques/blob/app/pubspec.yaml#L32)).
<strike>
i tried  add the package flutter_math_fork: ^0.3.0 like yours, it needs tuple 2.0.0(which depends quiver 2.0.0) but your pupspec.yaml not contains tuple, also google sign in depends quiver 3.0.0 , i am stuck

</strike>

thanks,
i solved ;

dependencies:
    quiver: ^2.0.0+1
dependency_overrides:
    quiver: "3.0.0"

**Comment by yavuztarhan** [comment]
@MuratovArthur 

> @Skyost
> 
> Hey!
> 
> Thank you for helping me!
> 
> I've tried to install the dev version from git, but it required to update some other packages. I've updated `sdk` to `sdk: ">=2.6.0 <3.0.0"`, `flutter_svg` to `flutter_svg: ^0.20.0-nullsafety.3`.
> 
> After that, I've tried to run my app, but there was an error `Error: Too few positional arguments: 8 required, 7 given. child: selectionControls!.buildToolbar(`.
> 
> Did you face such an error?)

how do you fix it ?
