### ISSUE TITLE
Package Incompatibility

### ISSUE THREAD

**Issue by melvinotieno** [znjameswu/flutter_math#45]
Because flutter_math <0.3.0-nullsafety.0 depends on tuple ^1.0.3 which depends on quiver >=0.22.0 <3.0.0, flutter_math <0.3.0-nullsafety.0 requires quiver >=0.22.0 <3.0.0.

(1) So, because google_sign_in_platform_interface >=2.0.0 depends on quiver ^3.0.0, flutter_math <0.3.0-nullsafety.0 is incompatible with google_sign_in_platform_interface >=2.0.0.

**Comment by walsha2** [comment]
This package is not being maintained any longer, it seems.

Please use this fork on Pub.dev instead:

https://pub.dev/packages/flutter_math_fork

This specific fork can be found here on Github:

https://github.com/simpleclub-extended/flutter_math
