### ISSUE TITLE
Special characters are unsupported

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [znjameswu/flutter_math#7]
If you try to use special characters like `ä` or `Ö` in a `FlutterMath` widget, it will not work.

It seems like the KaTeX fonts _need_ to support that as it works in KaTeX. What do you think @znjameswu 😃

**Comment by znjameswu** [comment]
Yes, I'm planning to support that. I'll work on it in next release.

**Comment by znjameswu** [comment]
Support for unicode accents is added in v0.1.8. Welcome to check out the online demo!

**Comment by znjameswu** [comment]
But one thing needs to mention is that i, j based unicode accent looks very unnatural (e.g. `ì`). This is inherited from KaTeX (see flutter_tex's output) and MathJaX does this job even worse. If you have any idea to fix this, please let me know.

**Comment by creativecreatorormaybenot** [comment]
@znjameswu Very awesome!

No, I have no idea. However, after looking into it, I think that it is not too bad. I mean the characters do look unnatural as you said, but they still fit into the rendered output generally. Before the change, they would not even have the correct metrics, so it is a huge improvement 🚀
